version: '3.8'

services:
  fastapi-e-commerce-api:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uv run uvicorn --host 0.0.0.0 --port 9000 main:app
#     depends_on:
#       - db

#   fastapi-e-commerce-db-postgres:
#     image: postgres:latest
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB:        ${POSTGRES_DB}
#       POSTGRES_USER:      ${POSTGRES_USER}
#       POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
#       POSTGRES_PORT:       ${POSTGRES_PORT}

# volumes:
#   postgres_data:./postgres_data
 
 