version: '3.8'

services:
  fastapi-e-commerce-api:
    build: .
    ports:
      - "${API_PORT}:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    # command: uv run uvicorn --host 0.0.0.0 --port 8000 main:app # this is already in Dockerfile
#     depends_on:
#       - db
    environment:
      - DEBUG=${DEBUG}
      - API_PORT=${API_PORT}

#   fastapi-e-commerce-db-postgres:
#     image: postgres:latest
#     ports:
#       - "${POSTGRES_PORT}:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB:        ${POSTGRES_DB}
#       POSTGRES_USER:      ${POSTGRES_USER}
#       POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
#       POSTGRES_PORT:       ${POSTGRES_PORT}

# volumes:
#   postgres_data:./postgres_data
 
 