version: '3.9'

services:
  fastapi-e-commerce-api:
    build:
      context: .
      target: ${DOCKER_BUILD_STAGE:-dev}
    volumes:
      - .:/app  # Mount current directory for live code updates in dev
      - /app/.venv  # Avoid mounting the virtual environment created by poetry
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env.${APP_ENV:-dev}
    environment:
      - DEBUG=${DEBUG}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
